import React, { useState } from "react";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Layout/Navbar";
import Title from "@/features/Youtube/Title";
import SlipCards from "@/features/Youtube/SlipCards";
import { Box } from "@mui/material";
// import Input from "@/features/Youtube/Input";
import Head from "next/head";

function Youtube() {
  const [finalKeyword, setFinalKeyword] = useState<string | null>(null);
//   const youtubeUrl = finalKeyword
//     ? `https://www.youtube.com/results?search_query=${encodeURIComponent(
//         finalKeyword
//       )}`
//     : "";

  return (
    <>
      <Head>
        <title>Youtube Streaming</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{ position: "relative", zIndex: 0 }}>
        <Box
          sx={{
            width: "100%",
            minHeight: "100vh",
            position: "relative",
            overflow: "hidden",
            display: "block",

            // Background image with transition
            "&::before": {
              content: '""',
              position: "absolute",
              inset: 0,
              backgroundImage: 'url("/background.png")',
              backgroundSize: "cover",
              backgroundPosition: "center",
              backgroundRepeat: "no-repeat",

              // Start state for animation
              opacity: 0,
              transform: "scale(1.02)",

              // Fade + zoom when page renders
              animation: "bgFadeZoom 0.8s ease-out forwards",

              // Extra blur + darken
              filter: "blur(4px) brightness(0.55)",

              zIndex: -2,
            },

            // Overlay gradient
            "&::after": {
              content: '""',
              position: "absolute",
              inset: 0,
              background:
                "linear-gradient(to bottom, rgba(0,0,0,0.4), rgba(0,0,0,0.6))",
              zIndex: -1,
            },
          }}
        >
          <Navbar />
          <Title />
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              width: "100%",
              alignItems: "center",
            }}
          >
            <SlipCards
              onFinish={(keyword) => {
                setFinalKeyword(
                  `https://www.youtube.com/results?search_query=${encodeURIComponent(
                    keyword
                  )}`
                );
              }}
            />
            {/* <Box sx={{ px: 16, width: "100%" }}>
              <Input url={youtubeUrl} />
            </Box> */}
          </Box>
        </Box>
      </main>
    </>
  );
}

export default Youtube;
